### ISSUE TITLE
Update README with motivation for this library

### ISSUE THREAD

**Issue by emartynov** [KingsMentor/RVcompose#3]
I guess I know why you want to use recycler view for UI like this. But would be great to fix this in the readme.

**Comment by KingsMentor** [comment]
A lot of applications follow a reusable UI pattern of design. I realized most design can be broken down into components that can be reused over and over again. Instead of having to design the layout of different screens, I resulted in designing layout for specific UI that can be reusable in a recyclerView. 
I have tried this approach in a couple of applications and it works great and allows me to build and add a new screen faster. It also helped improved updating views with changes in Models. 

RVcompose is an underlying library that provides a structure for designing other applications using this pattern.

**Comment by emartynov** [comment]
Thank you, for us, it also fixes the issue with nested scroll performance when you combining things.

**Comment by KingsMentor** [comment]
This is very true. I will update ReadMe with this. Thanks.

**Comment by emartynov** [comment]
Great!
